
services:
  mongo:
    image: mongo:latest
    container_name: some-mongo
    networks:
      - lemoncode-challenge
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend  # O usa ./node-stack si prefieres Node.js
    container_name: backend-dotnet  # O backend-node si usas Node.js
    networks:
      - lemoncode-challenge
    environment:
      - TopicstoreDatabaseSettings__ConnectionString=mongodb://some-mongo:27017
      - ASPNETCORE_HTTP_PORTS=5000  # Cambiar a 5000 si el backend usa este puerto

    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: lemoncode-frontend
    networks:
      - lemoncode-challenge
    environment:
      - API_URI=http://backend-dotnet:5000/api/topics  # O backend-dotnet si usas .NET
    depends_on:
      - backend
    ports:
      - "8080:8080"

networks:
  lemoncode-challenge:
    name: lemoncode-challenge


volumes:
  mongo-data:
