pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Code checked out from repository'
            }
        }

        stage('Compile') {
            steps {
                 dir('04-CI-CD/01-Jenkins/calculator') {
                    sh 'chmod +x gradlew'
                    sh './gradlew compileJava'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('04-CI-CD/01-Jenkins/calculator') {
                    sh './gradlew test'
                }
            }
        }
    }


    post {
        always {
            dir('04-CI-CD/01-Jenkins/calculator') {
                junit 'build/test-results/test/*.xml'
            }
        }
    }
}

